# Generated by Django 3.2.8 on 2021-10-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('las', '0002_generate_receipt_number_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectaccumulation',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Наименование клиента'),
        ),
    ]
